# Generated by Django 4.1 on 2022-11-08 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must not consist of space and requires country code. eg : +6591258565",
                        regex="^(\\+\\d{1,3})?,?\\s?\\d{8,13}",
                    )
                ],
            ),
        ),
    ]
