# Generated by Django 4.1 on 2022-08-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.DecimalField(decimal_places=0, max_digits=13),
        ),
    ]
