# Generated by Django 4.1 on 2022-08-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_remove_book_author_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(max_length=3000),
        ),
    ]
