# Generated by Django 4.1 on 2022-08-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_alter_book_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="pages",
            new_name="length",
        ),
    ]
