# Generated by Django 4.1 on 2022-08-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_rename_pages_book_length"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="length",
            new_name="pages",
        ),
    ]
