# Generated by Django 4.1 on 2022-08-22 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_alter_book_isbn_alter_review_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]*$", "ISBN contains numbers not words!"
                    ),
                    django.core.validators.MinLengthValidator(13),
                ],
            ),
        ),
    ]
