# Generated by Django 4.1 on 2022-08-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0013_review_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.CharField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=5,
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(related_name="books", to="books.author"),
        ),
    ]
