# Generated by Django 4.1 on 2022-08-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0016_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
            ),
        ),
    ]
