# Generated by Django 4.1 on 2022-10-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0017_alter_review_rating"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["id"], name="books_book_id_ffa80d_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["book"], name="books_revie_book_id_68ab4d_idx"),
        ),
    ]
