# Generated by Django 4.1 on 2022-10-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0018_book_books_book_id_ffa80d_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="book",
            name="books_book_id_ffa80d_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="books_revie_book_id_68ab4d_idx",
        ),
    ]
