# Generated by Django 4.1 on 2022-11-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0022_author_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="about",
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
