# Generated by Django 4.1 on 2022-11-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0024_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
    ]
