# Generated by Django 4.1 on 2022-11-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0025_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
