# Generated by Django 4.1 on 2022-11-18 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0027_remove_book_favorite_book_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="favorite",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
