# Generated by Django 4.1 on 2022-11-18 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0028_alter_book_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="favorite",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
