# Generated by Django 4.1 on 2022-11-18 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0030_alter_book_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="favorite",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_books", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
