# Generated by Django 4.1 on 2022-11-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0031_alter_book_favorite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["id"]},
        ),
    ]
