# Generated by Django 4.1 on 2022-11-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0033_book_add_date_book_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="add_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
