# Generated by Django 4.1 on 2022-11-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0034_alter_book_add_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="add_date",
            field=models.DateTimeField(),
        ),
    ]
