# Generated by Django 4.1 on 2022-11-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0036_alter_book_add_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.AddField(
            model_name="review",
            name="add_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
