# Generated by Django 4.1 on 2022-11-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0037_alter_book_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="date_added",
        ),
        migrations.AlterField(
            model_name="review",
            name="add_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
