# Generated by Django 4.1 on 2022-11-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0038_remove_review_date_added_alter_review_add_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="add_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="update",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="add_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="update",
            new_name="updated_at",
        ),
    ]
