# Generated by Django 4.1 on 2022-11-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0039_rename_add_date_book_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="books", to="books.author"
            ),
        ),
    ]
