# Generated by Django 4.1 on 2022-11-21 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0040_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="books.category",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="books/images"),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]*$", "ISBN contains numbers not words!"
                    ),
                    django.core.validators.MaxLengthValidator(13),
                ],
            ),
        ),
    ]
