# Generated by Django 4.1 on 2022-11-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0042_alter_book_author_alter_book_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(null=True, upload_to="books/images"),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
