# Generated by Django 4.1 on 2022-11-28 13:13

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0044_alter_author_name_alter_book_publisher"),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name="book",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="book_title_gin_index"
            ),
        ),
    ]
