# Generated by Django 4.1 on 2022-11-28 17:05

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0047_alter_book_isbn"),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name="book",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="NewGinIndex"
            ),
        ),
    ]
