# Generated by Django 4.1 on 2022-11-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0050_alter_author_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="book",
            name="NewGinIndex",
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
