# Generated by Django 4.1 on 2022-11-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0051_remove_book_newginindex_alter_book_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="publish",
        ),
    ]
