# Generated by Django 4.1 on 2022-11-30 06:12

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0052_remove_book_publish"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["title"], name="book_title_idx"
            ),
        ),
    ]
